baseURL = "https://match.ctl.columbia.edu/"
googleAnalytics = "UA-51144540-13"
metaDataFormat = "yaml"
languageCode = "en-us"
theme = "ctl-book"
title = "Multidisciplinary Approaches to Children\u2019s Oral Health (MATCH)"

[params]
    customCSS = "main.css"
    description = "MATCH is a set of online learning modules which can also serve as resources for practicing and future pediatric dentists to learn how they can work with other health care professionals to ensure a child\u2019s oral health and overall well-being. Children\u2019s oral health is determined by social, behavioral, genetic, nutritional, and educational factors--as well as by dental care. MATCH is an innovative effort to demonstrate how partnering with experts from these fields can enhance a dentist\u2019s practice and help children and their families obtain the highest levels of oral health."
    keywords = "dental education, oral healthcare, medicine, dentistry, pediatric dentistry"
    shortTitle = "MATCH"
