baseURL = "http://kodos.ccnmtl.columbia.edu/"
metaDataFormat = "yaml"
languageCode = "en-us"
theme = "ctl-book"
title = "Multidisciplinary Approaches to Children's Oral Health (MATCH)"

[params]
    customCSS = "main.css"
    description = "MATCH is a set of online learning modules which can also serve as resources for practicing and future pediatric dentists to learn how they can work with other health care professionals to ensure a child's oral health and overall well-being. Children's oral health is determined by social, behavioral, genetic, nutritional, and educational factors--as well as by dental care. MATCH is an innovative effort to demonstrate how partnering with experts from these fields can enhance a dentist's practice and help children and their families obtain the highest levels of oral health."
    keywords = "dental education, oral healthcare, medicine, dentistry"
    shortTitle = "MATCH"
